###
GET http://localhost:3000/

###
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "user_demo@mail.com",
    "password": "PassWord123"
}

###
GET http://localhost:3000/products

###
GET http://localhost:3000/auth

