### Crear
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "id": "ffffffff-0000-0000-0000-ffffffff1001",
  "name": "user",
  "email": "user@mail.com",
  "password": "PassWord@123",
  "confirmPassword": "PassWord@123",
  "phone": 321654,
  "country": "Perú",
  "address": "Calle Falsa 123",
  "city": "Lima",
  "error": "estes es una prueba"
}

###
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "user_demo@mail.com",
    "password": "PassWord@123"
}

### 
GET http://localhost:3000/users