@token=Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZmZmZmZmZi0wMDAwLTAwMDAtMDAwMC1mZmZmZmZmZjAwMDEiLCJpZCI6ImZmZmZmZmZmLTAwMDAtMDAwMC0wMDAwLWZmZmZmZmZmMDAwMSIsImVtYWlsIjoidXNlcl9kZW1vQG1haWwuY29tIiwiaWF0IjoxNzMxNzI3MzUwLCJleHAiOjE3MzI1OTEzNTB9.K8cVZUAOggSG0cyjE4GnbQ3p7PaxBrSs-ksosjUp6N8


### 
POST http://localhost:3000/category/seeder 
Content-Type: application/json
Authorization: {{token}}

### 
POST http://localhost:3000/category
Content-Type: application/json
Authorization: {{token}}

{
  "id": "aaaaaaaa-0000-0000-0000-aaaaaaaa1001",
  "name": "smartphone"
}

### 
GET http://localhost:3000/category

### 
GET http://localhost:3000/category/aaaaaaaa-0000-0000-0000-aaaaaaaa0001

### 
PATCH http://localhost:3000/category/aaaaaaaa-0000-0000-0000-aaaaaaaa0001
Content-Type: application/json
Authorization: {{token}}

{
  "name": "smartphoneUpdate"
}

### 
DELETE http://localhost:3000/category/aaaaaaaa-0000-0000-0000-aaaaaaaa0001
Authorization: {{token}}
