@token_admin=Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZmZmZmZmZi0wMDAwLTAwMDAtMDAwMC1mZmZmZmZmZjAwMDEiLCJpZCI6ImZmZmZmZmZmLTAwMDAtMDAwMC0wMDAwLWZmZmZmZmZmMDAwMSIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJyb2xlcyI6WyJ1c2VyIl0sImlhdCI6MTczOTIxMjE0MSwiZXhwIjoxNzQwMDc2MTQxfQ.74jlwOBote4ShvWZDHzr-DtlPmSO_qkg0kuLU_CsB2g


### 
POST http://localhost:3000/order
Content-Type: application/json
Authorization: {{token_admin}}

{
  "id": "eeeeeeee-0000-0000-0000-eeeeeeee1001",
  "userId": "ffffffff-0000-0000-0000-ffffffff0001",
  "products": [
    {
      "id": "bbbbbbbb-0000-0000-0000-bbbbbbbb0001"
    },
    {
      "id": "bbbbbbbb-0000-0000-0000-bbbbbbbb0002"
    }
  ]
}

### 
GET http://localhost:3000/order

### 
GET http://localhost:3000/order/eeeeeeee-0000-0000-0000-eeeeeeee1001
Authorization: {{token_admin}}

### 
PATCH http://localhost:3000/order/eeeeeeee-0000-0000-0000-eeeeeeee1001
Content-Type: application/json
Authorization: {{token_admin}}

{
  "id": "eeeeeeee-0000-0000-0000-eeeeeeee1001",
  "userId": "ffffffff-0000-0000-0000-ffffffff0001",
  "products": [
    {
      "id": "bbbbbbbb-0000-0000-0000-bbbbbbbb0005"
    },
    {
      "id": "bbbbbbbb-0000-0000-0000-bbbbbbbb0006"
    }
  ]
}

### 
DELETE http://localhost:3000/order/eeeeeeee-0000-0000-0000-eeeeeeee1001
Content-Type: application/json
Authorization: {{token_admin}}
