### Crear un nuevo usuario
POST http://localhost:3000/order
Content-Type: application/json

{
  "id": "eeeeeeee-0000-0000-0000-eeeeeeee1001",
  "userId": "ffffffff-0000-0000-0000-ffffffff0001",
  "products": [
    {
      "id": "bbbbbbbb-0000-0000-0000-bbbbbbbb0001"
    },
    {
      "id": "bbbbbbbb-0000-0000-0000-bbbbbbbb0002"
    }
  ]
}

### Obtener todos los usuarios
GET http://localhost:3000/order

### Obtener un usuario por ID
GET http://localhost:3000/order/eeeeeeee-0000-0000-0000-eeeeeeee1001

### Actualizar un usuario por ID
PATCH http://localhost:3000/order/eeeeeeee-0000-0000-0000-eeeeeeee1001
Content-Type: application/json

{
  "id": "eeeeeeee-0000-0000-0000-eeeeeeee1001",
  "userId": "ffffffff-0000-0000-0000-ffffffff0001",
  "products": [
    {
      "id": "bbbbbbbb-0000-0000-0000-bbbbbbbb0005"
    },
    {
      "id": "bbbbbbbb-0000-0000-0000-bbbbbbbb0006"
    }
  ]
}

### Eliminar un usuario por ID
DELETE http://localhost:3000/order/eeeeeeee-0000-0000-0000-eeeeeeee1001
