### seeder
POST http://localhost:3000/product/seeder
Content-Type: application/json
Authorization: Basic: <email>:<password>.

### Crear 
POST http://localhost:3000/product
Content-Type: application/json
Authorization: Basic: <email>:<password>.

{
  "id": "bbbbbbbb-0000-0000-0000-bbbbbbbb1001",
  "name": "product 1",
  "description": "product 1 description",
  "stock": 10,
  "price": 100,
  "category": "smartphone",
  "imgUrl": "https://picsum.photos/200/300"
}

### product
GET http://localhost:3000/product

### product
GET http://localhost:3000/product?page=1&limit=20

### 
GET http://localhost:3000/product/bbbbbbbb-0000-0000-0000-bbbbbbbb0001

### PATCH
PATCH http://localhost:3000/product/bbbbbbbb-0000-0000-0000-bbbbbbbb0001
Content-Type: application/json
Authorization: Basic: <email>:<password>.

{
  "name": "Update product 1",
  "description": "Update product 1 description",
  "stock": 10,
  "price": 100,
  "category": "smartphone",
  "imgUrl": "https://picsum.photos/200/300"
}

### Eliminar 
DELETE http://localhost:3000/product/bbbbbbbb-0000-0000-0000-bbbbbbbb0001
Content-Type: application/json
Authorization: Basic: <email>:<password>.

### all
DELETE http://localhost:3000/product/all
Content-Type: application/json
Authorization: Basic: <email>:<password>.