### seeder
POST http://localhost:3000/product/seeder
Content-Type: application/json
Authorization: Basic: <email>:<password>.

### Crear 
POST http://localhost:3000/product
Content-Type: application/json
Authorization: Basic: <email>:<password>.

{
  "id": "bbbbbbbb-0000-0000-0000-bbbbbbbb0001",
  "name": "product 1",
  "description": "product 1 description",
  "stock": 10,
  "price": 100,
  "category": "smartphone",
  "imgUrl": "https://picsum.photos/200/300"
}

### Obtener todos los usuarios
GET http://localhost:3000/product

### Obtener un usuario por ID
GET http://localhost:3000/product/bbbbbbbb-0000-0000-0000-bbbbbbbb0001

### Actualizar un usuario por ID
PATCH http://localhost:3000/product/bbbbbbbb-0000-0000-0000-bbbbbbbb0001
Content-Type: application/json
Authorization: Basic: <email>:<password>.

{
  "name": "Update product 1",
  "description": "Update product 1 description",
  "stock": 10,
  "price": 100,
  "category": "smartphone",
  "imgUrl": "https://picsum.photos/200/300"
}

### Eliminar un usuario por ID
DELETE http://localhost:3000/product/bbbbbbbb-0000-0000-0000-bbbbbbbb0001
Content-Type: application/json
Authorization: Basic: <email>:<password>.

### all
DELETE http://localhost:3000/product/all
Content-Type: application/json
Authorization: Basic: <email>:<password>.