@token=Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZmZmZmZmZi0wMDAwLTAwMDAtMDAwMC1mZmZmZmZmZjAwMDEiLCJpZCI6ImZmZmZmZmZmLTAwMDAtMDAwMC0wMDAwLWZmZmZmZmZmMDAwMSIsImVtYWlsIjoidXNlcl9kZW1vQG1haWwuY29tIiwiaWF0IjoxNzMxNzI3MzUwLCJleHAiOjE3MzI1OTEzNTB9.K8cVZUAOggSG0cyjE4GnbQ3p7PaxBrSs-ksosjUp6N8


###
GET http://localhost:3000/users
Authorization: {{token}}

###
GET http://localhost:3000/users?page=1&limit=1
Authorization: {{token}}

###
GET http://localhost:3000/users/ffffffff-0000-0000-0000-ffffffff0001
Authorization: {{token}}

###
PATCH http://localhost:3000/users/ffffffff-0000-0000-0000-ffffffff0001
Content-Type: application/json
Authorization: {{token}}

{
  "name": "userUpdate",
  "email": "userUpdate@mail.com",
  "password": "Password@123",
  "phone": 321654,
  "country": "country",
  "address": "address 123",
  "city": "city"
}

###
DELETE http://localhost:3000/users/ffffffff-0000-0000-0000-ffffffff0001
Content-Type: application/json
Authorization: {{token}}
