@token_admin=Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZmZmZmZmZi0wMDAwLTAwMDAtMDAwMC1mZmZmZmZmZjAwMDEiLCJpZCI6ImZmZmZmZmZmLTAwMDAtMDAwMC0wMDAwLWZmZmZmZmZmMDAwMSIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJyb2xlcyI6WyJ1c2VyIl0sImlhdCI6MTczOTIxMjE0MSwiZXhwIjoxNzQwMDc2MTQxfQ.74jlwOBote4ShvWZDHzr-DtlPmSO_qkg0kuLU_CsB2g
###
@token_user=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZmZmZmZmZi0wMDAwLTAwMDAtMDAwMC1mZmZmZmZmZjAwMDEiLCJpZCI6ImZmZmZmZmZmLTAwMDAtMDAwMC0wMDAwLWZmZmZmZmZmMDAwMSIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJyb2xlcyI6WyJ1c2VyIl0sImlhdCI6MTczOTIxMjE0MSwiZXhwIjoxNzQwMDc2MTQxfQ.74jlwOBote4ShvWZDHzr-DtlPmSO_qkg0kuLU_CsB2g


###
GET http://localhost:3000/users
Authorization: {{token_admin}}

###
GET http://localhost:3000/users?page=1&limit=1
Authorization: {{token_admin}}

###
GET http://localhost:3000/users/ffffffff-0000-0000-0000-ffffffff0001
Authorization: {{token_admin}}

###
PATCH http://localhost:3000/users/ffffffff-0000-0000-0000-ffffffff0001
Content-Type: application/json
Authorization: {{token_admin}}

{
  "name": "userUpdate",
  "email": "userUpdate@mail.com",
  "password": "Password@123",
  "phone": 321654,
  "country": "country",
  "address": "address 123",
  "city": "city"
}

###
DELETE http://localhost:3000/users/ffffffff-0000-0000-0000-ffffffff0001
Content-Type: application/json
Authorization: {{token_admin}}
