
###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "New Product",
  "description": "Description 1",
  "price": 100,
  "stock": 1,
  "imgUrl": "https://picsum.photos/200/300"
}

###
GET http://localhost:3000/products

###
GET http://localhost:3000/products?page=1&limit=1

###
GET http://localhost:3000/products/2

###
PUT http://localhost:3000/products/1
Content-Type: application/json

{
  "name": "Update Product",
  "description": "Description 1",
  "price": 100,
  "stock": 1,
  "imgUrl": "https://picsum.photos/200/300"
}

###
DELETE http://localhost:3000/products/1
