
###
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Basic: <email>:<password>.

{
  "email": "new@j.com",
  "name": "new",
  "address": "new",
  "phone": 321654,
  "country": "country",
  "city": "city"
}

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users?page=1&limit=2

###
GET http://localhost:3000/users/1

###
PUT http://localhost:3000/users/2
Content-Type: application/json
Authorization: Basic: <email>:<password>.

{
  "email": "update@j.com",
  "name": "update",
  "address": "update",
  "phone": 321654,
  "country": "country",
  "city": "city"
}

###
DELETE http://localhost:3000/users/1
Content-Type: application/json
Authorization: Basic: <email>:<password>.