@token=Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZmZmZmZmZi0wMDAwLTAwMDAtMDAwMC1mZmZmZmZmZjAwMDEiLCJpZCI6ImZmZmZmZmZmLTAwMDAtMDAwMC0wMDAwLWZmZmZmZmZmMDAwMSIsImVtYWlsIjoidXNlcl9kZW1vQG1haWwuY29tIiwiaWF0IjoxNzMxNzI3MzUwLCJleHAiOjE3MzI1OTEzNTB9.K8cVZUAOggSG0cyjE4GnbQ3p7PaxBrSs-ksosjUp6N8

### seeder
POST http://localhost:3000/product/seeder
Content-Type: application/json
Authorization: {{token}}

### Crear 
POST http://localhost:3000/product
Content-Type: application/json
Authorization: {{token}}

{
  "id": "bbbbbbbb-0000-0000-0000-bbbbbbbb1001",
  "name": "product 1",
  "description": "product 1 description",
  "stock": 10,
  "price": 100,
  "category": "smartphone",
  "imgUrl": "https://picsum.photos/200/300"
}

### product
GET http://localhost:3000/product

### product
GET http://localhost:3000/product?page=1&limit=20

### 
GET http://localhost:3000/product/bbbbbbbb-0000-0000-0000-bbbbbbbb0001

### PATCH
PATCH http://localhost:3000/product/bbbbbbbb-0000-0000-0000-bbbbbbbb0001
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Update product 1",
  "description": "Update product 1 description",
  "stock": 10,
  "price": 100,
  "category": "smartphone",
  "imgUrl": "https://picsum.photos/200/300"
}

### Eliminar 
DELETE http://localhost:3000/product/bbbbbbbb-0000-0000-0000-bbbbbbbb0001
Content-Type: application/json
Authorization: {{token}}

### all
DELETE http://localhost:3000/product/all
Content-Type: application/json
Authorization: {{token}}