### info
GET http://localhost:3000/system/info

### time
GET http://localhost:3000/system/time

### infoDatabase
GET http://localhost:3000/system/infoDatabase

### entities
GET http://localhost:3000/system/entities

### endpoints
GET http://localhost:3000/system/endpoints

### package.json
GET http://localhost:3000/system/package.json

### domain
GET http://localhost:3000/system/domain
Content-Type: application/json
Authorization: 1234

### cookies
GET http://localhost:3000/system/cookies

### resetDatabase
DELETE http://localhost:3000/system/resetDatabase

### runMigrations
POST http://localhost:3000/system/runMigrations
